# This is my alacritty configuration file
# From Sebastian Mohr

import = [
    "~/.dotfiles/alacritty/themes/mos-tokyo-night.toml"
]

[window]
   opacity = 0.85
   blur = true
   padding = { x = 4, y = 4 }
   dynamic_padding = true
   decorations = "None" # Remove this as soon as switched to Hyprland


[keyboard]
# spawn new alacritty instance by pressing Ctrl+Shift+Return
   bindings = [
      { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
   ]

[font]
   normal = { family = "JetBrainsMonoNLNerdFontMono", style = "Regular" }
   size = 14

